### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by sortaloc** [exmex/DCNC#28]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
  - bug report

# What is the current behavior?
> If the current behavior is a bug, please provide the steps to reproduce and if possible logs from all the servers (upload it to gist or pastebin)

I've compiled on my own, and when I try to run it I get this error on server

# What is the expected behavior?
Can login into the client

# Other informations
> e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc

Before I can use compiled server that given from my friends, but after I run my own compiled server files, I can't run my friend's server with the same error. When I delete the database I can't auto create accounts

# Log Files
> Please upload ALL logfiles from log/ to pastebin.com **DO NOT POST THE ONES FROM ARCHIVE!**

https://pastebin.com/gxPnerWG
![screenshot_2](https://user-images.githubusercontent.com/1770300/31326275-e983c2ea-acef-11e7-9b68-33ffd7c1b892.png)
![screenshot_3](https://user-images.githubusercontent.com/1770300/31326276-e985590c-acef-11e7-8280-37375fd7b2de.png)

**Comment by FadedAssassiin** [comment]
Have you created a account? if so, go into the AuthServer.exe and enter 

> CREATE <username> <password>

Registering a ID and Password respectively.

**Comment by FadedAssassiin** [comment]
Have you created a account? if so, go into the AuthServer.exe and enter 

`CREATE <username> <password>`

Registering a ID and Password respectively.

**Comment by Cigneture** [comment]
Have you created a account? If you have not, go into the AuthServer.exe and enter 

`CREATE <username> <password>`

Registering a ID and Password respectively.

**Comment by exmex** [comment]
@FadedAssassiin it's not that he has no account. He's missing a table which should have been deleted like ~30-40 commits ago.

```
2017-10-09 12:26 [Info] - Killing off client. Table 'dcmm.servers' doesn't exist:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at Shared.Models.ServerModel.Retrieve(MySqlConnection dbconn) in D:\Danang\workspace\DCNC-0.2.974.47.0779db-master\src\Shared\Models\ServerModel.cs:line 25
   at Shared.Network.AuthServer.UserAuthPacket.OnPacket(Packet packet, MySqlConnection connection) in D:\Danang\workspace\DCNC-0.2.974.47.0779db-master\src\Shared\Network\Packets\AuthServer\UserAuthPacket.cs:line 91
   at AuthServer.Network.Handlers.Authentication.UserAuth(Packet packet) in D:\Danang\workspace\DCNC-0.2.974.47.0779db-master\src\AuthServer\Network\Handlers\Auth.cs:line 21
   at Shared.Network.DefaultServer.Parse(Packet packet) in D:\Danang\workspace\DCNC-0.2.974.47.0779db-master\src\Shared\Network\DefaultServer.cs:line 221
   at Shared.Network.Client.OnData(IAsyncResult result) in D:\Danang\workspace\DCNC-0.2.974.47.0779db-master\src\Shared\Network\Client.cs:line 116
```

You're using an outdated version. Namely 0779db. I can also see this since it still says: Special Thanks to amPe**a**rl and was fixed in a later version since his name is amPerl not amPearl. So please update to the newest version, and try again.

**Comment by sortaloc** [comment]
Okay, I'll try to compile it again with updated version, Thanks

**Comment by exmex** [comment]
I'm closing this for now.
